### ISSUE TITLE
Initialize a build pipeline for Linux and Windows

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/DevAtServ#1]
Hi,

Goal is to have a kind of OneInAll installer similar to RobotFramework AIO.
Nothing else shall be required to be installed to get the Micro Service System run. 
Manual testing shall be possible by means of using the GUI, automated testing shall be possible by means of using the RabbitMQ APIs.

For the Linux-Installer Linux the RabbitMQ Docker image can be used if useful, required python packages and tools can be dependencies.
For Windows-Installer RabbitMQ and Erlang need to be part of the installer. Not clear: which python and microservices.
In both cases the installer need to take care of proper pre-configuration that when installation finished the system is fully functional without any further configuration.

Therefore a build pipeline should be initialized which follow steps
- Clone our repos: 
  - [python-microservice-base](https://github.com/test-fullautomation/python-microservice-base) 
  - [python-microservice-cleware-switch](https://github.com/test-fullautomation/python-microservice-cleware-switch)
- Install OSS packages: 
   - **RabbitMQ** 
   - **Erlang** 
   - nodejs
   - python3
   
- Build:
   - Windows Installer: InnoSetup script (can also containt docker images if this makes sense on Windows)
   - Linux Installer: Debian package (can contain docker images)
   - Documentation: genpackagedoc

Installer for both, Windows and Linux shall install all what is required _completely independent_ of RobotFramework AIO.
Start-> click at `DevAtServ GUI`-Icon shall start the MicroService GUI.
 
Other jobs (Test, Release) can be added later.
Scripts can be referred from Robotframework_AIO repo.

**Comment by huavanthong** [comment]
Hi Thomas,

As the result in meeting, I would like to update this ticket.

### **About RabbitMQ**

Currently, after installing Docker on Windows and Linux platforms, users can install RabbitMQ using the following command:
```
docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.13-management
```
* `docker run:` Command to run a docker container

* `-it`: This allows us to interact with the container's terminal.
* `--rm`:  automatically removed the container when it exits.
* `--name rabbitmq`:  assigns the name "rabbitmq" to the container
* `-p 5672:5672 -p 15672:15672`: These flags map ports from the container to ports on the host machine. RabbitMQ typically uses port 5672 for AMQP communication and port 15672 for the management interface. By specifying -p 5672:5672 -p 15672:15672, we expose these ports on the host machine, allowing us to access RabbitMQ from outside the container.
* `rabbitmq:3.13-management`: This is the name and tag of the Docker image used to create the container. In this case, it specifies the RabbitMQ image with version 3.13 and the management plugin enabled.

### **About other service**
* [python-microservice-base](https://github.com/test-fullautomation/python-microservice-base): Run it by command
```
$env:RobotPythonPath\python.exe .\MicroserviceBase\ServiceRegistry\ServiceRegistry.py
```
* [python-microservice-cleware-switch](https://github.com/test-fullautomation/python-microservice-cleware-switch): Run it by command
```
$env:RobotPythonPath\python.exe .\MicroserviceClewareSwitch\ServiceCleware.py
```

### **About AIO tools**
The user can develop the Robot script to run the service above.



That's all for my info. If you have any concerns, please tell me.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
This is in work. Testing from other team members is missing.

**Comment by test-fullautomation** [comment]
Stabilization is in progress. Build pipelines exist.
